### ISSUE TITLE
4.3.0-SNAPSHOT no longer available

### ISSUE THREAD

**Issue by DarkAtra** [nitrite/nitrite-java#1015]
I just noticed that the `4.3.0-SNAPSHOT` release [is no longer available](https://github.com/DarkAtra/v-rising-discord-bot/actions/runs/10332522604/job/28603847926#step:4:22) in https://oss.sonatype.org/content/repositories/snapshots
I was using that version in my project since [the graalvm hints](https://github.com/nitrite/nitrite-java/pull/995) are not included in a stable release yet. Would it be possible to either create a stable release that includes them or create another snapshot for the time being?

**Comment by anidotnet** [comment]
v4.3.0 is already released. I have published 4.3.1-SNAPSHOT with your latest PRs.

**Comment by DarkAtra** [comment]
v4.3.0 did not include the initial graalvm pr though ^^ that's why i was asking. ty for the new snapshot
