### ISSUE TITLE
"Split package" (JPMS) issue

### ISSUE THREAD

**Issue by alexei-osipov** [nitrite/nitrite-java#1035]
Currently Nitrite is released as multiple JARs with different parts of functionality (that's good).

However these JARs have overlapping package names for some classes causing "split package" problem and triggering errors if Java Platform Module System (JPMS) is used in the app that depends on Nitrite main JAR and `nitrite-jackson-mapper` JAR.

For instance, there are classes for package `org.dizitart.no2.common.mapper` in both `org.dizitart:nitrite` and `org.dizitart:nitrite-jackson-mapper` JARs.

As result, when JPMS is enabled, app gets errors like this:
```
error: the unnamed module reads package org.dizitart.no2.common.mapper from both org.dizitart.no2.jackson and org.dizitart.no2
```

Possible solution: move classes of  `nitrite-jackson-mapper`  from package `org.dizitart.no2.common.mapper` to a dedicated non-overlapping package like `org.dizitart.no2.common.mapper.jackson`.

**Comment by anidotnet** [comment]
Thanks for reporting the issue. I need to take a look at this and push the fix in next release.
