### ISSUE TITLE
Support for composite IDs

### ISSUE THREAD

**Issue by sheinbergon** [nitrite/nitrite-java#130]
Hello.

Browsing through the source code, it seems only a single field can be annotated with `@Id` (otherwise, an exception is thrown). is there any particular reason why composite (as in composed of multiple fields annotated with the `@Id` annotation) IDs are not supported?

**Comment by anidotnet** [comment]
I have developed nitrite keeping simplicity in mind. For an embedded database single id seems sufficient for most of the use cases. You can use unique indexes for other fields which will serve the same purpose.

That being said, supporting composite key (creating id on custom object data type) along with other features (like spatial indexing, array indexing) are already in the roadmap for next major release.

**Comment by anidotnet** [comment]
Feature is added in 4.0.1-SNAPSHOT
