### ISSUE TITLE
Use Websockets for Datagate Communication

### ISSUE THREAD

**Issue by TareqK** [nitrite/nitrite-java#201]
Datagate should probably be using websockets instead of relying on polling clients

**Comment by TareqK** [comment]
https://github.com/TareqK/nitrite-datagate 

for the curious, ive opened a repository and started a from-scratch project here at @anidotnet  request. Still not finalized, still havent finished the spec, but i invite anybody who wants to give feedback to give it there

**Comment by anidotnet** [comment]
Change implemented in 4.0.0
