### ISSUE TITLE
Please add BETWEEN Filter

### ISSUE THREAD

**Issue by mmariuzzo** [nitrite/nitrite-java#215]
Hi, I have a NitriteDB collection with 9M of objects; increasing by 200k elements month. 
Collected objects have a "receivedTime" field (a long) and I have an NonUnique index on it.

To retrieve a week of objects I'm using

```
Filter filter = Filters.and(
       Filters.gte("receivedTime", startDate.getTime()),
       Filters.lt("receivedTime", endDate.getTime()));

Cursor cursor = collection.find(filter, FindOptions.sort("receivedTime", SortOrder.Ascending));
```

but I've had to increase heap memory to make this query to complete 

If I've understand the internal logic, these two conditions are applied separately and then the result is joined.

Suppose my query identify 20k objects in the middle of the collection. 

First filter (gte) collect 4.5M of ids. Second one collect 4.5M of ids. Then these sets are combined to return the right 20k.

Having a "BETWEEN" filter the two conditions could be applied in a single round with a big memory gain, and also query time

**Comment by anidotnet** [comment]
It's a good idea. I'll try to address this in the next major version. Meantime you can roll your own custom filter by implementing `Filter` interface. You can try that in your app.

**Comment by anidotnet** [comment]
Implementation added in 4.0.0-SNAPSHOT
