### ISSUE TITLE
Using pagination with No filter, lead to o(n) request time

### ISSUE THREAD

**Issue by frett27** [nitrite/nitrite-java#216]
The use case is to permit users to navigate the set, using pagination.
Or permit to have batch synchronizations.

when no filter is set to find in the collection, a set is constructed from the full keyset. This id construct take o(n) time complexity, just to grab the proper ids (fetch is not done yet). On large datasets, this is not usable. 

https://github.com/dizitart/nitrite-database/blob/74b0522ad952b5ed7cbc1a03dd6fb22873094aae/nitrite/src/main/java/org/dizitart/no2/internals/SearchService.java#L110

an alternative is to use the underlying natural ordering of the MVStore to get the initial ids from BTree, this can then open the library to large datasets.

**Comment by anidotnet** [comment]
I admit the current search strategy is not optimal due to its eager nature. This is currently being improved in 4.x version with lazy streams.

**Comment by frett27** [comment]
Any view on this ? i'd like to contribute on 4.x on this topic, i setup a parser for filters, and wish to refactor the search / indexing feature (keeping ids does not properly scale, for 30k + records)

**Comment by anidotnet** [comment]
Have a look at the new design - https://github.com/anidotnet/nitrite-java

**Comment by frett27** [comment]
sorry for using this channnel, but are there any communication channel about this or PM / IRC i can use for exchanging ?

**Comment by anidotnet** [comment]
@frett27 I have added you in a team - @nitrite/nitrite-java-dev , let's discuss there.

**Comment by frett27** [comment]
hi, Anindya seems the link is broken. thank's for your help

**Comment by anidotnet** [comment]
@frett27 I have sent u an invitation for the team. Check your emails, once you accept the invitation you can join the discussion.

**Comment by anidotnet** [comment]
Hi @frett27 I just realized that the team discussion channel is only visible to team members but it is not publicly visible. So let us move our discussion further on gitter public channel - https://gitter.im/dizitart/nitrite-database for everybody's sake. I have sent an invitation to you to join.

**Comment by frett27** [comment]
hi anindya,

Thank's for your message, i didn't had the time to setup, this will come, i
have some personal dead lines thoses days.
yes indeed this is interesting to have a public thread.

thank you

Patrice

**Comment by anidotnet** [comment]
Improvement implemented in 4.0.0-SNAPSHOT
