### ISSUE TITLE
repository.register is instance related but db.getRepository return different instances

### ISSUE THREAD

**Issue by ylyxf** [nitrite/nitrite-java#217]
when  register an ChangeListener like this:
<pre>
objectRepository = db.getRepository(clazz);
repository.register(new ChangeListener() { ....});
</pre>
then in another class :
<pre>
objectRepository = db.getRepository(clazz);
objectRepository.insert(object); 
</pre>
but the ChangeListener  does not fired  as expect.

after some test, i found that  listeners are  instance related ,but db.getRepository return different instances. we should always use the same objectRepository instance for crud which is registered by ChangeListeners.

it would be great to explain this feature  in document ‘7.5. Events’.

**Comment by frett27** [comment]
I had the same issue, it seems the registration is done "per" collection instance

**Comment by anidotnet** [comment]
Fix should be available in 4.0.0-SNAPSHOT
