### ISSUE TITLE
True composite-index support

### ISSUE THREAD

**Issue by sheinbergon** [nitrite/nitrite-java#228]
Hello.

While nitrite currently provides a means to query multiple indices in a single run,  achieving the same filtering capabilities as a composite index would, under the hood, it splits filters onto separate threads and tries to run them in parallel.

While this is OK for most use-cases, in some compute environments where scheduling resources (cpu cores) are under contention, this might prove to be sub-optimal, resulting in orders of mangitude slower query times (1000 of microseconds instead of just tens)

True composite indices would alleviate this issue and would allow more complex queries to finish much faster.

If I was to contribute such a feature, would you be willing to accept a PR?

**Comment by sheinbergon** [comment]
@anidotnet This would also make https://github.com/nitrite/nitrite-java/issues/130 very easy to implement.

**Comment by anidotnet** [comment]
Excellent suggestion. I would like to point out that effort is currently underway to rebuild nitrite from ground up in version 4.x. Code is currently in my personal repo - https://github.com/anidotnet/nitrite-java. I'll suggest you to get familiarized with the new api first as lots of breaking changes are there and documentation is not ready yet.

Meantime, I'll merge the code in this repo on a separate branch. If you want to contribute, I'll suggest you to work on that branch. Let me know what you think.

**Comment by sheinbergon** [comment]
@anidotnet not sure I understand your instructions:

- Would you like to receive this contribution for the current version, or only for the complete rewrite? or both?
- WIll you keep a separate branch for version 3.x hotfixes in the future?

**Comment by anidotnet** [comment]
To answer your questions

- I would like to receive the contribution on top of the complete rewrite code not the current codebase.
- Ofcourse I'll keep a separate branch for 3.x fixes, but no new changes will go there.

Having said that, I have not added the complete rewrite code (4.x) here in this codebase. If you are ready to start working for the contribution, I'll add the new code here in a new branch (4.x) in this codebase. Then you provide your changes on 4.x branch only.

**Comment by anidotnet** [comment]
Hi @sheinbergon just checking, would you still be interested in pursuing this? If you are, please take the code from the develop branch.

**Comment by anidotnet** [comment]
Feature is added in 4.0.1-SNAPSHOT
