### ISSUE TITLE
Performance issue during insert entry to collection

### ISSUE THREAD

**Issue by aukhatov** [nitrite/nitrite-java#230]
Hi!
I've faced to performance issue when my Nitrite DB larger than **4Gb**.
How many data in Gb do you recommend storing?

**Comment by anidotnet** [comment]
Can you elaborate what kind of performance issue are you facing? Normally there is no limit of storage size, but it depends on what kind of data are you storing, are you using indexing properly or not etc.

**Comment by aukhatov** [comment]
After ~3.6Gb inserting new documents become to slowly than earlier

**Comment by aukhatov** [comment]
Of course I do index

**Comment by anidotnet** [comment]
Could you provide some reproducible code? Meantime if you are using multiple collections, you can try to use one db per collection if possible (like application level partitioning) to reduce the load.

**Comment by aukhatov** [comment]
@anidotnet piece if code to put data or get?

**Comment by aukhatov** [comment]
I also noticed after insert all my data to db, the db size was a huge about 150Gb.
And happened something interesting, when I did a query the db size was decreased to 87Gb.

**Comment by aukhatov** [comment]
@anidotnet There is piece of code to reproduce it. If you have some problems, you'll text me.

Insert code example:
```java
public static void insertItems(Path pathToMetadata) {
        try (Nitrite db = Nitrite.builder()
                .filePath(dbPath)
                .openOrCreate(userName, password)) {

            try (NitriteCollection collection = db.getCollection("item")) {

                if (!collection.hasIndex("listId"))
                    collection.createIndex("listId", indexOptions(IndexType.NonUnique, true));
                    
                Properties prop = new Properties();
                try (BufferedReader br = Files.newBufferedReader(Paths.get(pathToMetadata))) {
                             prop.load(br);
                }
                
                insert(collection, prop);
            }
        }
}
    
private static void insert(NitriteCollection collection, Properties prop) {
            Set<Object> keySet = prop.keySet();
            Document doc = new Document();
    
            for (Object key : keySet) {
                final String keyValue = (String) key;
                doc.put(keyValue, prop.getProperty(keyValue));
            }
    
            collection.insert(doc);
}
```

data example:

file **my_data.properties**
```properties
    ContentTypeId=0x001F2C9072206BEE41BC16A728F0327437
    OData__UIVersionString=1.0
    md_FileRef=/sites/aukhatov3/_catalogs/theme/15/Palette002.spcolor
    File_x0020_Type=spcolor
    md_id=ae59515f-f10e-4340-93fd-905d5b02983b
    Modified=2020-01-12T08\:58\:48Z
    md_etag="1"
    ID=4
    UniqueId=9cf03c71-9adf-4f60-8031-82f25507d5f9
    FileSystemObjectType=0
    md_type=SP.Data.OData__x005f_catalogs_x002f_themeItem
    md_FileLeafRef=Palette002.spcolor
    md_uri=https\://domain.sharepoint.com/sites/aukhatov3/_api/Web/Lists(guid'72902c1f-6b20-41ee-bc16-a728f0327437')/Items(4)
    AuthorId=1073741823
    md_RelatedDocument=676b32c3-a13e-45e0-9462-905aee6ffde2.spcolor-@-20200601080218
    md_ParentGuid=28bc954f-cbdc-4ad0-a56d-aead6c141816
    Id=4
    md_Url=https\://domain.sharepoint.com/sites/aukhatov3/_catalogs/theme/15/Palette002.spcolor
    EditorId=1073741823
    Created=2020-01-12T08\:58\:48Z
    md_Author=System Account
    md_FileSizeDisplay=5251
    md_Folder=/_catalogs/theme/15
    GUID=676b32c3-a13e-45e0-9462-905aee6ffde2
```

**Comment by aukhatov** [comment]
I load my data via Properties (JDK) because all of the data are represented as .properties.

**Comment by aukhatov** [comment]
@anidotnet And for the completely reproduce this issue you should insert **1505088**  entries.

**Comment by aukhatov** [comment]
@anidotnet Hi!
Could you explain me about **ChangeFeed**? 
According to official doc https://www.dizitart.org/nitrite-database/#replication the ChangeFeed will store only when Replication is enabled. Is it right? Or the Nitrite has some unusual cases for that?

**Comment by aukhatov** [comment]
I think the ChangeFeed may increase my db size (:

**Comment by anidotnet** [comment]
First of all your db size decreases from 150GB to 87GB due to compaction of db file. You need to choose what best serve your purpose. Having an index will also increase file size, but you only create index if it helps in you query.

Secondly I have never tested with this much of data. With this amount of data other factors also comes into calculation like your disk performance (SSD will have better performance), memory availability etc. Personally I believe a traditional database server is best suited for your use case, where you can use nitrite as second level cache to store a subset of data which is frequently being used. Nitrite is powered by mvstore engine of h2 database, where user of that database often complained about decreased performance with large file size.

`ChangeFeed` is a POJO to hold the changes in a collections, it is only enabled during replication and resides only in memory.

**Comment by aukhatov** [comment]
@anidotnet Thanks! But your answer upset me.

**Comment by anidotnet** [comment]
You can test your code with v4 branch - https://github.com/nitrite/nitrite-java/tree/4.x. It is a complete rewrite of nitrite with lots of braking changes to the api. The api is not freezed yet and obviously this version is not published. You have to build from the source and use it in your code and check if it improves anything or not.

**Comment by aukhatov** [comment]
@anidotnet Thank you!
It sounds interesting, I'll do that.

**Comment by aukhatov** [comment]
I'm going to come back with feedback :)

**Comment by aukhatov** [comment]
@anidotnet When do you plan to release a new version of the Nitrite?

**Comment by anidotnet** [comment]
No date has been finalized yet. Need to complete the new documentation and also I am writing a typescript version of nitrite. When these 2 complete I'll release the new version.

**Comment by anidotnet** [comment]
> I'm going to come back with feedback :)

Feedback is what I need most for the new nitrite. :smile:

**Comment by aukhatov** [comment]
@anidotnet I have built the v4.x of the Nitrite.
What does it mean that log message: 
`18:16:43.158 [main] DEBUG org.dizitart.no2.collection.SnowflakeIdGenerator - SNOWFLAKE: initialised with node id 80` ? I've got it during "SELECT" query.

**Comment by aukhatov** [comment]
### About the db file size
Unfortunately in the new version the db file size is greater that previous version.
```
nitrite-no-index-v3.db  3,4G
nitrite-no-index-v4.db  4,3G
```
Of course I've uploaded the same data.

**Comment by aukhatov** [comment]
I've heard the SNOWFLAKE is a kind of algorithm which invented by Twitter to generate unique id. Is it right?

**Comment by anidotnet** [comment]
Don't worry about size of the file, check if you are noticing any performance improvement. And you are right about snowflake. It is to generate an unique id across different devices

**Comment by aukhatov** [comment]
Is there some difference do compress before insert and after?

**Comment by aukhatov** [comment]
DB file size is an important character for me. I want to reduce it.

**Comment by anidotnet** [comment]
While using builder, use `compressed()` to compress the database and make sure autoCompact is enabled (i.e. you have not called `disableAutoCommit()` on builder)

**Comment by aukhatov** [comment]
@anidotnet about performance in Nitrite v4. I've done several experiments as a result worse than v3 about ~10 sec.

**Comment by aukhatov** [comment]
For example, I do the same query. And I've got the results:

- **v3** - `61688 ms`
- **v4** - `70598 ms`

**Comment by anidotnet** [comment]
Is it possible to share the experimental project? As the development is not completed yet, I have not looked into the performance side.

**Comment by aukhatov** [comment]
@anidotnet I think, yes. But without any data which I've inserted to the database. I will share it later...

**Comment by aukhatov** [comment]
@anidotnet Could you explain me please, how compression works?
I've inserted my data without any compression and I've seen one result. And then I do some query with .compress and the db file size hasn't changed. Is it okay?
But another way, I've inserted me data with .compress and I've seen the db file size is lower than I expect.
It seems a compress doesn't work after data is inserted to the database. What do you think?

**Comment by anidotnet** [comment]
Here is the documentation of mvstore in details - https://www.h2database.com/html/mvstore.html. Compression is discussed there.

**Comment by aukhatov** [comment]
@anidotnet Can I set some memory limit before loading the whole Nitrite DB into memory?

**Comment by anidotnet** [comment]
Sorry you can't setup any db memory limit in nitrite.

**Comment by anidotnet** [comment]
In 4.0.0-SNAPSHOT, rocksdb storage adapter has been added which has much better performance in high writes and db size is also consistent. Code is there in develop branch and artifacts are there in maven snapshot repository. There are breaking api changes in 4.x, so please consult the test classes if you want to use 4.x, until the documentation is ready.
