### ISSUE TITLE
Problem with com.fasterxml.jackson.module.kotlin.KotlinModule dependency with Spring Boot. Which version to use?

### ISSUE THREAD

**Issue by drgb88** [nitrite/nitrite-java#244]
Getting stuck on this error using Spring Boot and com.fasterxml.jackson.module.kotlin.KotlinModule
Same message with either 2.9.5 or 2.11.0 version of com.fasterxml.jackson.module.kotlin
Attempts to strictly use or exclude version 2.11.0 have not worked, same error. I am new to Nitrite, so thanks for any help. Geoffrey
gradle build file attached.
[build.gradle.txt](https://github.com/nitrite/nitrite-java/files/4900533/build.gradle.txt)

Error message:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.dizitart.kno2.KNO2JacksonFacade.createObjectMapper(KNO2JacksonFacade.kt:40)

The following method did not exist:

    'void com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(int, boolean, boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)'

The method's class, com.fasterxml.jackson.module.kotlin.KotlinModule, is available from the following locations:

    jar:file:/home/drgb/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-kotlin/2.9.5/3e73e80ff0285a776954252f61c22e4059ee5267/jackson-module-kotlin-2.9.5.jar!/com/fasterxml/jackson/module/kotlin/KotlinModule.class

The class hierarchy was loaded from the following locations:

    com.fasterxml.jackson.module.kotlin.KotlinModule: file:/home/drgb/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-kotlin/2.9.5/3e73e80ff0285a776954252f61c22e4059ee5267/jackson-module-kotlin-2.9.5.jar
    com.fasterxml.jackson.databind.module.SimpleModule: file:/home/drgb/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.11.0/8f5aaf3878b0647ff3a16610af53b1a5c05d9f15/jackson-databind-2.11.0.jar
    com.fasterxml.jackson.databind.Module: file:/home/drgb/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.11.0/8f5aaf3878b0647ff3a16610af53b1a5c05d9f15/jackson-databind-2.11.0.jar

**Comment by anidotnet** [comment]
You should use latest version of potassium nitrite - 3.4.2 and jackson-module-kotlin - 2.10.1

```gradle

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.61'
    id 'org.springframework.boot' version '2.3.1.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
}

group 'org.dizitart.demo'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation('org.dizitart:potassium-nitrite:3.4.2')
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.10.1")

    implementation("org.springframework.boot:spring-boot-starter-web")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

compileKotlin {
    kotlinOptions.jvmTarget = "11"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "11"
}
```

**Comment by drgb88** [comment]
Yes, version 2.10.1 did the trick! Thanks, now onto the next error.
G.
