### ISSUE TITLE
Add support to Arrays/Lists in Document

### ISSUE THREAD

**Issue by ironluca** [nitrite/nitrite-java#246]
It would be good to have the capability to update (add/remove) elements from an array in a document akin to Mongo $push-$each. Instead of now getting the array, adding element to it and then updating the whole array.

**Comment by anidotnet** [comment]
As nitrite is an embedded database, this update operation would be better handled in the application code. It does not make much difference if I put this logic in database, as the steps will be similar. Instead we could save the database code from unnecessary bloating.
