### ISSUE TITLE
Add nitrite-bom?

### ISSUE THREAD

**Issue by Double-O-Seven** [nitrite/nitrite-java#255]
Hi there, I've seen that the number of projects on the 4.x branch is growing. How about adding a `nitrite-bom` project (here is an example from my own projects: https://github.com/Double-O-Seven/stubr/blob/master/stubr-bom/build.gradle.kts)?

This would be great for people using the `java-platform` Gradle plugin (see https://docs.gradle.org/current/userguide/java_platform_plugin.html).

**Comment by anidotnet** [comment]
That's a good suggestion. I'll have a look at it.

**Comment by anidotnet** [comment]
Nitrite bom support added in 4.x branch. Snapshot version is available in maven snapshot repository.

You can add in maven dependency as

```xml

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.dizitart</groupId>
            <artifactId>nitrite-platform</artifactId>
            <version>4.0.0-SNAPSHOT</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

or in gradle as 

```groovy
implementation platform('org.dizitart:nitrite-platform:4.0.0-SNAPSHOT')
```

**Comment by Double-O-Seven** [comment]
@anidotnet Why not name it `nitrite-bom`? If you look at popular projects, they all name it with suffix `-bom`:
* guava-bom
* guice-bom
* protobuf-bom
* junit-bom
* netty-bom
* jackson-bom

I think it would be much more clear if you'd name it `nitrite-bom` according to the convention such that people immediately understand that it's the bill of materials.

**Comment by anidotnet** [comment]
Good point, you are right. Let me rename it. I am never good with names. :)

**Comment by anidotnet** [comment]
Done.
