### ISSUE TITLE
Potasium Nitrite should just use ThreeTenABP by jakeWharton

### ISSUE THREAD

**Issue by thegarlynch** [nitrite/nitrite-java#301]

**Comment by anidotnet** [comment]
I don't want to add this backport dependency to potassium nitrite. If someone wants to use java.time in their project then why do they need a backport dependency? 

There is a test class already available as an example - https://github.com/nitrite/nitrite-java/blob/master/potassium-nitrite/src/test/kotlin/org/dizitart/kno2/BackportJavaTimeTest.kt if people want to use it in their project.
