### ISSUE TITLE
Two simultaneous instances

### ISSUE THREAD

**Issue by clbj1** [nitrite/nitrite-java#316]
Hi,

It's more a doubt. I'm trying create connections with two or more Nitrite databases (distincts files) simultaneously, but doing that, results in too many consistence errors (didn't find content, database is alread in use...). 
With one single connection per time, everithing runs right.

The API suports simultaneous connections or it's not possible do that?

Thanks in advance!

**Comment by anidotnet** [comment]
The api should support multiple nitrite instances with distinct data files. But if you are seeing something otherwise, please report it here with some reproducible code.

**Comment by anidotnet** [comment]
I have created a test, it shows that simultaneous connects is supported.

```kotlin
package test

import com.github.javafaker.Faker
import org.dizitart.kno2.nitrite
import java.io.Serializable
import java.nio.file.Files
import java.nio.file.Paths


fun main(args: Array<String>) {
    val faker = Faker()
    val db1 = nitrite {
        path = "/tmp/users1.db"
    }

    val db2 = nitrite {
        path = "/tmp/users2.db"
    }

    val repo1 = db1.getRepository(User::class.java)
    val repo2 = db2.getRepository(UserInfo::class.java)

    for (i in 0..10) {
        val user = User(faker.name().firstName(), faker.name().lastName())
        repo1.insert(user)

        val userInfo = UserInfo(faker.name().firstName(), faker.name().lastName())
        repo2.insert(userInfo)
    }

    println("----User----")
    for (user in repo1.find()) {
        println(user)
    }

    println("----UserInfo----")
    for (userInfo in repo2.find()) {
        println(userInfo)
    }

    db1.close()
    db2.close()

    Files.delete(Paths.get("/tmp/users1.db"))
    Files.delete(Paths.get("/tmp/users2.db"))
}

data class User(val firstName: String, val lastName: String) : Serializable
data class UserInfo(val firstName: String, val lastName: String) : Serializable
```

**Comment by anidotnet** [comment]
Create a new issue if you see any specific problem. And try to provide as much info as possible about the issue, a reproducible code could be of much help.

**Comment by clbj1** [comment]
Hi,

Thanks for the support, that's more than enought to help me. 
I'm evaluating my application, if I find some problem I will put all logs together and mount an example.


Thanks again. Regards.

Cesar
