### ISSUE TITLE
Slow query on index with sort

### ISSUE THREAD

**Issue by tadas-subonis** [nitrite/nitrite-java#329]
We have this query:

![image](https://user-images.githubusercontent.com/247218/94680433-02762280-0322-11eb-8617-e7a1f4287980.png)

and there is an index for the "date" field (NonUnique type).

The queries are extremely slow when there are ~100k entries. It takes ~3s to retrieve the data. The limit is at ~20 entries.

That's how profiler results look like:
![image](https://user-images.githubusercontent.com/247218/94680548-33565780-0322-11eb-956c-a24b5c792a9a.png)

Is there anything wrong the way we are using it or maybe nitrite doesn't support sorts via indices?

**Comment by anidotnet** [comment]
Currently nitrite does not support sorting via indices.

**Comment by anidotnet** [comment]
Feature is added in 4.0.1-SNAPSHOT
