### ISSUE TITLE
Geospatial Indexing

### ISSUE THREAD

**Issue by kennywk** [nitrite/nitrite-java#34]
Would be nice if the documents/objects can support geospatial indexing/queries.

The property could be a geojson object representation and the querying/indexing can be performed using the JTS library.

Ex:

`public class Place{
private String name;
private GeoJson location;
}`

`
Cursor cursor = collection1.find().where("location").within(polygon);
Cursor cursor = collection1.find().where("location").near(point,distance);
Cursor cursor = collection1.find().where("location").intersects(geojson);
`

I've used JTS before, and there is a Jackson Library for serializing/deserializing the JTS Geometry objects to GeoJson. I think this feature would also provide universal value to others as it is becoming a pretty standard feature within DBs.

Thanks.

**Comment by anidotnet** [comment]
Honestly, I don't have any experience with geospatial operations. Care to contribute?

**Comment by kennywk** [comment]
Sure, will see what I can do once I get back to my office.

**Comment by kennywk** [comment]
I'm trying to get the gradle environment working correctly... seems to be
giving me problems. However i have noticed that your using enough of the
right libraries to implement geospatial queries/indexing rather easily...
would just need to know what you'd prefer with regards to placement.

**Comment by anidotnet** [comment]
I did not understand what is the "placement" you are referring to. 

By the way it is the error you are facing currently with gradle?

**Comment by kennywk** [comment]
Yes, it is a gradle thing, basically not wanting to retrieve/get the
necessary dependencies.

By placement i  am referring to what classes/pattern/location you would
prefer that i place the code. I can put it inside the cursor classes, but
it seems as if the logic is done somewhere else. I'll continue looking into
the code to get better familiar with the flow.

**Comment by anidotnet** [comment]
For query, you need to create different filters like ```WithinFilter```, ```NearFilter``` etc. Take a look into other filters like```AndFilter```, ```EqualFilter``` etc. You need to create functions like ```within```, ```near``` in ```Filters``` class also. For special treatment in query you need to modify general query logic in ```SearchService``` and ```IndexedSearchService``` class. For indexing, take a look into ```IndexingService``` class. 

For pojos, you need to work on similar classes under ```objects``` package.

**Comment by kennywk** [comment]
Cool, i'll look into it.... Any recommendations for the dependency issues?
I normally use maven and it provides the ability within netbeans to
download the necessary dependencies.... with gradle i'm not sure.

**Comment by kennywk** [comment]
Anindya,

Unfortunately, until i can get gradle to download the necessary
dependencies i will be unable to add contributions. I have an idea of what
i need to do, but my lack of knowledge with gradle and the ability for the
ide to get the necessary jars has kept me from doing being able to do
anything.

K

**Comment by anidotnet** [comment]
Can you please run this below command in the project root dir?

```
./gradlew clean assemble -x test --info --stacktrace
```

If it fails, check if you are behind proxy firewall or not. If you are, then provide the proxy information in the command line

```
./gradlew -Dhttp.proxyHost=<http proxy host> -Dhttp.proxyPort=<http proxy port> -Dhttps.proxyHost=<https proxy host> -Dhttps.proxyPort=<http proxy port> clean assemble -x test --info --stacktrace
```

If it still fails then let me know the error details here. If the build passes, then you should open your project in either IntelliJ or eclipse. If you face any problem in just opening the project in IDE, you can go through numerous resource on net on how to do that or let me know here.

**Comment by anidotnet** [comment]
Are you still pursuing this?

**Comment by kennywk** [comment]
Anindya,

Yes, i've worked on it some and have a basic implementation minus a
btree/STR indexing. Still looking at how to integrate the actual indexing
method. The existing code is not so clear.

**Comment by anidotnet** [comment]
Indices in nitrite are just maps stored in database for reverse lookup. These maps are basically ```MVMap```s which implements B+ trees. The same ```MVMap``` also stores documents and objects in nitrite. So it is just more maps for indices. You should look at these 3 files to understand its inner working

- https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/internals/IndexingService.java
- https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/internals/IndexedSearchService.java
- https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/internals/IndexMetaService.java

```IndexingService``` is for indexing the collections. ```IndexedSearchService``` is used to search on indexed fields and ```IndexMetaService``` stores metadata for indices for easy lookup.

I don't know how indexing works for geospatial data also don't know if it is possible to implement geospatial indexes using maps. But if it helps you can also take a look at the full-text indexing logic here

- Nitrite's own ```NitriteTextIndexingService``` https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/internals/NitriteTextIndexingService.java
- Lucene based text indexing https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/test/java/org/dizitart/no2/services/LuceneService.java

Let me know if you need anything specific.

**Comment by kennywk** [comment]
There are multiple types of indexes based upon what your trying to do. Some
popular ones are R-Tree, B-Tree and QuadTree.... Obviously the Tree portion
of the name means that they can be key/value. I will take a look when i get
time and see how it can be implemented.

K

**Comment by anidotnet** [comment]
I hope things are going well for you. Just wanted to check if you have done any progress on this. Have you considered geohash for the implementation?

**Comment by kennywk** [comment]
Hey thanks for message. I’ve made some progress but have not had time to invest. Geohashing works pretty good for points but I’m not sure if it would work for geometries

**Comment by anidotnet** [comment]
Fair enough.

**Comment by anidotnet** [comment]
Spatial indexing support has been added to 4.0.0-SNAPSHOTS
