### ISSUE TITLE
opening nitrite from another process

### ISSUE THREAD

**Issue by amiracam** [nitrite/nitrite-java#369]
Sorry, this may be just a Windows thing, but I"m hoping there's another mechanism.
I'm trying to copy s nitrite db while its still opened from another process.
I'm basically trying to get a copy so that I can do read only analysis of the data without affecting the online transaction processing.
However, windows does not allow me due to: 
"The process cannot access the file because another process has locked a portion of the file ...."

Does nitrite allow multiple processes to open it ? Is it possible and / or advisable to have a secondary read only process open a NitriteDB datafile ?

I also notice that there's an Exporter for Nitrite, is it possible to export Nitrite while it maybe actively be under update ?

thanks

**Comment by anidotnet** [comment]
Sorry for late reply. The behavior you are explaining is not windows specific only. Nitrite db file can not be opened from two different processes. 

If you want another instance, you just need to create a copy of the data file before opening the database, but it will not be in sync with the rw instance, whatever write operation you will perform will not be available in the readonly instance.
