### ISSUE TITLE
Data accessible on File Database

### ISSUE THREAD

**Issue by LuccaPrado** [nitrite/nitrite-java#373]
Even my connection using storage and password, when its not open I can see on notepad the data that is stored.

Example:
this class:
![image](https://user-images.githubusercontent.com/8813731/98445018-1288db00-20f4-11eb-8b16-cbefa2245deb.png)
Generate this:
![image](https://user-images.githubusercontent.com/8813731/98445007-fbe28400-20f3-11eb-9174-ecf8b4080f04.png)

There are some solution to stop that? Or I would need to use an external cryptography system?

**Comment by LuccaPrado** [comment]
Related to:
[issue 209](https://github.com/nitrite/nitrite-java/issues/209#issuecomment-592108226)

**Comment by anidotnet** [comment]
Nitrite does not use encryption for storage. The password is for enforcing user level access, not to encrypt data. You need to use external cryptography system to encrypt data and store it as a bytes.
