### ISSUE TITLE
OkHttp usage prevents nitrite from being used with android SDKs lower than 21

### ISSUE THREAD

**Issue by lahiruchandima** [nitrite/nitrite-java#393]
I upgraded nitrite from version 3.3.0 to 3.4.2, an it looks like OkHttp has been added as a dependency to nitrite, which causes my app to crash on android SDK versions below 21 due to below restriction.

https://github.com/square/okhttp/issues/4481

The crash actually doesn't happen in nitrite itself, but in another library, which depends on a previous version of OkHttp, which is now forced to use the newer version of OkHttp due to the newer version dependency through nitrite.

Would it be OK to remove the transitive dependency to OkHttp through nitrite, so that the previous version of OkHttp will be used, which would fix my issue? I am not doing anything which requires nitrite to communicate through internet, so I think this should be fine. It would be great if you could confirm this.

Thank you

**Comment by anidotnet** [comment]
Yeah, you can go ahead and use the old version of okhttp.
