### ISSUE TITLE
Update nested Documents

### ISSUE THREAD

**Issue by tmoliveira** [nitrite/nitrite-java#451]
Hello,

I am facing an issue, I don't if it is something wrong with my implementation, or if it is a bug. I am using an ObjectRepository to store objects, which implements the Mappable interface. One of the fields of my objects is a Map. For the write and read Mappable methods I am transforming the map in a nested Document, and vice-versa. This works fine. I am able to insert/find my object to/from the repository and access this Map. The problem is when I am trying to update this map field on the object. To do this i am creating a filter with the Id of my object and a Document to update with the nested Document (which works on the insert operation). However I am getting and exception: **object must implements Mappable**. 

What is the best way to store a nested Map in an object, assuming that this Map value may be primitive types or Mappable objects?

Thanks in advance.

**Comment by anidotnet** [comment]
Sorry for belated response. Could you please provide a reproducible code? I have not fully understood what exactly you are trying to achieve.

**Comment by anidotnet** [comment]
Feature is added in 4.0.1-SNAPSHOT
