### ISSUE TITLE
Distributed application

### ISSUE THREAD

**Issue by flatlanderer** [nitrite/nitrite-java#475]
I'd like to ask how can we use Nitrite for a distributed application? 

**This would mean**
- Concurrent access to the database from multiple applications (multiple thread, multiple processes)
- Using GlusterFS as the persistent disk to achieve maximum storage elasticity for each nodes (in other words, don't get disk full problems)

**Comment by anidotnet** [comment]
Nitrite is an embedded database, only a single process at a time can access the database file for read and write operation. Once the database file in opened in a process, other process cannot open the file. But in a single process the database can be accessed by multiple threads.

Nitrite is not like traditional server side database system, it does not comes with a database server. Here the idea is that the database system is embedded in your application as a library. It is ideal for mobile application or desktop application or small server side application where only one instance is accessing the database.
