### ISSUE TITLE
When I tried to Access Nitrite DB in Websphere , i am facing IllegalArgumentException  at NitriteMVStore.java at openMap method

### ISSUE THREAD

**Issue by Aravind-2018** [nitrite/nitrite-java#529]
cause : java.lang.ClassNotFoundException: org.dizitart.no2.NitriteId
detailMessage : Could not deserialize [-84, -19, 0, 5, 115, 114, 0, 26, 111, 114, 103, 46, 100, 105, 122, 105, 116, 97, 114, 116, 46, 110, 111, 50, 46, 78, 105, 116, 114, 105, 116, 101, 73, 100, 0, 0, 0, 0, 88, 16, 73, 103, 2, 0, 1, 76, 0, 7, 105, 100, 86, 97, 108, 117, 101, 116, 0, 16, 76, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 76, 111, 110, 103, 59, 120, 112, 115, 114, 0, 14, 106, 97, 118, 97, 46, 108, 97, 110, 103, 46, 76, 111, 110, 103, 59, -117, -28, -112, -52, -113, 35, -33, 2, 0, 1, 74, 0, 5, 118, 97, 108, 117, 101, 120, 114, 0, 16, 106, 97, 118, 97, 46, 108, 97, 110, 103, 46, 78, 117, 109, 98, 101, 114, -122, -84, -107, 29, 11, -108, -32, -117, 2, 0, 0, 120, 112, 0, 0, 76, 8, -47, 87, 102, -88] [1.4.198/0]

Using Nitrite version 3.4.3
H2 Version 1.4.198

**Comment by anidotnet** [comment]
It is a class loading issue at websphere I suppose. You need to dig down the class loading details of your server, then only you will know why NitriteId class is not available in classpath.
