### ISSUE TITLE
Mappable Documentation not fully explicit about storing field with @Id annotation?

### ISSUE THREAD

**Issue by Doc1faux** [nitrite/nitrite-java#547]
Hi,

I've just experienced troubles about a class implementing the [Mappable](https://www.dizitart.org/nitrite-database/#mappable) interface.
I had an annotated `@Id int nitriteId` field in it stored in a document under the `nitrite_id` key overriding the `write` method.
I've encountered an `InvalidIdException: id can not be null` and diving into the implementation, I've found reflection is used to retrieve the annotated `@Id` field and then its name is used as key to found it in the document. 
However in my case, the field name and the key being different (`nitriteId` vs. `nitrite_id`), it did not found the annotated `@Id` field in the document.

Maybe it should be worth to clarify this use case in the [Mappable](https://www.dizitart.org/nitrite-database/#mappable) section of the documentation? :)

One step further may be to use also the `@SerializedName` annotation instead of the field name as key in the document?
It's just an idea, I'm fine with the current behavior, just laking a bit of explanation about it ;)

Best regards

**Comment by anidotnet** [comment]
Thanks for reporting. I have not considered this use case actually. I'll add necessary steps in documentation as well as in v4.x of nitrite.

**Comment by anidotnet** [comment]
Feature is added in 4.0.1-SNAPSHOT
