### ISSUE TITLE
Add coroutines to KNO2

### ISSUE THREAD

**Issue by bahmanebazoo** [nitrite/nitrite-java#623]
I need to add coroutines flow for observing data and changes.
I'll start it soon. I'll be appreciate if you have any scheduled backlog for it let me know with witch I could cooperate. othervise please review its pull request in the future.

and in advance thanks for your reply.
best regard Bahman Bazoo

**Comment by anidotnet** [comment]
Hi @bahmanebazoo I have not started anything on coroutines. You can start your work from develop branch if you want to contribute. Thanks for the initiatives.
