### ISSUE TITLE
[Question] Is it possible to search for similar terms?

### ISSUE THREAD

**Issue by yuripourre** [nitrite/nitrite-java#634]
Hey, firstly, thanks for this great project, it is super useful.

I've been doing a few experiments and sometimes I have to search using terms that contains typos. Do you have any recommendation to search entries that a certain attribute is similar to a certain text?

I know I can try to use regex but it is not the same.

**Comment by anidotnet** [comment]
You can create a full-text index on that specific field and use `text` filter to take advantage of the full-text search engine.

**Comment by yuripourre** [comment]
@anidotnet thank you! I will try
