### ISSUE TITLE
No user map found in the database on open

### ISSUE THREAD

**Issue by envas** [nitrite/nitrite-java#684]
I have an app that creates a new database on first reboot using

``` 
JacksonMapper nitriteMapper = new JacksonMapper(new TimeFacade());
nitriteMapper.getObjectMapper().registerModule(module);
db = Nitrite.builder().nitriteMapper(nitriteMapper).compressed().filePath(CBOX_DB_FILENAME).openOrCreate("sa", "sa");
``` 

then a reboot occurs. Normally it works well, now I got the following error message on reboot

```
org.dizitart.no2.exceptions.SecurityException: NO2.7002: no user map found in the database
    org.dizitart.no2.Security.openSecurely(82)
    org.dizitart.no2.NitriteBuilder.openOrCreateInternal(457)
    org.dizitart.no2.NitriteBuilder.openOrCreate(415)
```

The issue was solved - delete the database and create a new on.  I would like to know, what happened here. I created a lot of database like this one and I never noticed this error. Should I avoid compressed to increase the stability?

**Comment by anidotnet** [comment]
I would suggest disabling compression and compaction. Because sometimes MVStore create issues with them.
