### ISSUE TITLE
02/2022 current CVEs

### ISSUE THREAD

**Issue by sscholl** [nitrite/nitrite-java#691]
Hello,

when will the current CVEs of the dependency h2-mvstore-1.4.200.jar be solved?
https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ah2database&cpe_product=cpe%3A%2F%3Ah2database%3Ah2&cpe_version=cpe%3A%2F%3Ah2database%3Ah2%3A1.4.200 

Thanks
Simon

**Comment by anidotnet** [comment]
First of all these CVEs are for h2 database, not for h2 mvstore library. Secondly, there are breaking changes in h2 mvstore 2.x. Database file created with h2 mvstore 1.4.x is not readable by h2 mvstore 2.x. So I don't think it is a priority now to upgrade the mvstore library version.

**Comment by sscholl** [comment]
@anidotnet thanks for the fast reply! So that means, h2-mvstore-1.4.200.jar is not affected and a false-positive?
