### ISSUE TITLE
ObjectRepository.find(ObjectFilter) returning null entries

### ISSUE THREAD

**Issue by Doc1faux** [nitrite/nitrite-java#706]
Hi @anidotnet :)

I faced an issue today on a search with a filtered index which returned me `null` values while expecting only objects causing a crash on my side. I'm currently using `v3.4.2` on Android.
I investigated a bit and while the library is creating the `FindResult` in the `SearchService.find(Filter)` method, the `Set<NitriteId> result` was containing 17 entries while the `NitriteMap<NitriteId, Document> underlyingMap`  was containing only 15. Then the `toList` method iterate on the 17 entries and add `null` entries for each entry it could not find in the `underlyingMap`.
It is like the index was not up-to-date :/
I dived into the code and I could not understand beyond the `IndexedSearchService.findEqual(String, Object)` method where the `NitriteMap<Comparable, ConcurrentSkipListSet<NitriteId>> indexMap` is instantiated which retrieves me the 17 index entries while there are only 15 in DB.

For the moment, the only choice I have is to drop `null` entries after the `toList` method :/

**Comment by anidotnet** [comment]
Can you please post a reproducible code here which can successfully recreate the issue you are facing?

**Comment by Doc1faux** [comment]
I @anidotnet,

I'm trying to write some sample code for it but struggle to reproduce the issue as it happens rarely :/
But once it happens, I could reproduce it each time because the index is corrupted pointing deleted entries.

I will update the issue when I will have a 100% reproducible use case.
Thanks for your patience.

**Comment by dveyarangi** [comment]
I have also encountered similar issue. It seems to be due to discrepancy between index and the underlyingMap. I could not reproduce this in a clean environment, because I do not understand how the db got to this shape.
Attaching the existing DB and the code that yields nulls from find()
Windows 11, Nitrite 3.4.4, JDK 8
[NitriteNullPointerIssue.zip](https://github.com/nitrite/nitrite-java/files/9127447/NitriteNullPointerIssue.zip)

**Comment by anidotnet** [comment]
Closed due to inactivity
