### ISSUE TITLE
Itermittent NPE in remove

### ISSUE THREAD

**Issue by cpotter1** [nitrite/nitrite-java#76]
In DataService, on line 227, seeing this problem periodically.

java.lang.NullPointerException
	at org.dizitart.no2.internals.DataService.remove(DataService.java:228)
	at org.dizitart.no2.internals.NitriteService.remove(NitriteService.java:372)
	at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:360)
	at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:349)
	at 

Looks like you are not checking for null on "removed" before calling getRevision:
            Document removed = underlyingMap.remove(nitriteId);
            int rev = removed.getRevision();

**Comment by anidotnet** [comment]
Can you please give me a reproducible code? The region from where it is throwing is as follows:

```java
for (Document document : cursor) {
    NitriteId nitriteId = document.getId();
    indexingService.removeIndexEntry(document, nitriteId);

    Document removed = underlyingMap.remove(nitriteId);
    int rev = removed.getRevision();  <<< NPE
```
It means that `nitriteId` is not there in the `underlyingMap`, but the `nitriteId` is obtained from a document iterating the cursor which is generated from the same `underlyingMap`.

So I am curious why is it happening. My initial assumption is, you are removing the document from a different thread and it is hitting a race condition. So If you could give me a reproducible code it would be better for me to dig down and take proper measure.

**Comment by cpotter1** [comment]
Hi Anindya, I am thinking the same thing as you... However, the problem is
very hard to reproduce.  Was hoping you could just write some defensive
code for this case.

**Comment by anidotnet** [comment]
@cpotter1 can you test the latest snapshot now? - 3.0.1-SNAPSHOT
