### ISSUE TITLE
Unique value constraint will not prevent db from getting updated

### ISSUE THREAD

**Issue by alebo611** [nitrite/nitrite-java#767]
Version; 3,4,4
How to reproduce:

Put a constraint on a string name for example:
@Indices({
        @Index(value = "name", type = IndexType.Unique)
})

Create two objects, with two distinct names.

Then, do an update on one of the objects with a name that is the same as the other object. 

Result: There will be an exception thrown from nitrite that the name is not unique, but the db still gets updated. So now there are two duplicates in the db.

**Comment by anidotnet** [comment]
Please use 4.1.0 SNAPSHOT. It has been fixed in 4.x branch
