### ISSUE TITLE
BUG: podam dependency is compile-scoped

### ISSUE THREAD

**Issue by bvfalcon** [nitrite/nitrite-java#771]
Last version of nitrite has compile-scoped dependency podam - [pom.xml](https://repo1.maven.org/maven2/org/dizitart/nitrite/3.4.4/nitrite-3.4.4.pom).
This is incorrrect: podam is test-scoped dependency, not compile.

Note: this is important because podam has dependencies validation-api and javax.annotation-api, which are not compatible with Jakarta EE. Therefore nitrite cannot be used in Jakarta EE 9-10 applications

**Comment by anidotnet** [comment]
Sorry for belated response. The recent version of nitrite 4.1.0-SNAPSHOT does not have that dependency.. You could try that.
