### ISSUE TITLE
Cannot remove entry on update

### ISSUE THREAD

**Issue by ruckustboom** [nitrite/nitrite-java#773]
If I have a document saved, there doesn't seem to be an obvious way to remove an existing field on that document.

```java
var doc = Document()
    .put("a", "1")
    .put("b", "2");
collection.insert(doc);
// doc is { a: 1, b: 2, _revision: 1, ... }

doc.put("a", "3");
doc.remove("b");
collection.update(doc);
// doc is { a: 3, b: 2, _revision: 2, ... }
// expected: { a: 3, _revision: 2, ... }
```

**Comment by Y2Kwastaken** [comment]
I myself am trying to work through this issue with little to no help. I've reverted to try to looking through source code, but again it has been over a year yet there seems to be no response on this issue.

Oddly enough this document remove behavior is extremely quirky so removing nested values is actually possible and pretty easy
```java

final var doc = createDocument();
final var internalDoc = createDocument();
internalDoc.put("a", "internal value");

doc.put("a", "1");;
doc.put("b", internalDoc);
collection.insert(doc);
/*
* doc is {"a": "1", b: {"a": "internal value"}}
*/

doc.put("a", "3")
doc.remove("b")
collection.update(doc);
/*
* doc is now {"a":"3", b:{}}
*/
```
I find this behavior extremely weird and the fact there has been no response to a somewhat simple issue after a year is extremely strange. I will look into this behavior more myself and may make a PR or fork depending on the activity of the project.

**Comment by anidotnet** [comment]
I'll take a look as soon as possible. I must have missed this issue somehow.

**Comment by anidotnet** [comment]
The update operation actually is a document merge operation. If you remove any field from the document, it will not be removed in the collection when you update the document, only existing fields will be updated.

From your use case what I understand that you need something like document replace operation. To achieve this, you have to remove the document from the collection first, modify it and insert it.
