### ISSUE TITLE
why OkHttp?

### ISSUE THREAD

**Issue by scancmdr** [nitrite/nitrite-java#782]
If nitrite is an embedded document store, why is there a dependency on an http client:

OkHttp is an HTTP client

![Screenshot from 2022-12-02 21-59-00](https://user-images.githubusercontent.com/5082905/205419307-1d5a4526-ae9d-4c36-9f4d-fe8d6791e077.png)

I don't want an http client in my embedded database...

**Comment by anidotnet** [comment]
OkHttp was introduced to connect to a DataGate server for two-way replication.
