### ISSUE TITLE
NitriteMapper does not give enough info about the type

### ISSUE THREAD

**Issue by lamba92** [nitrite/nitrite-java#815]
I wrote a kotlinx.serialization `NitriteMapper` and serialization format for `Document`s. All works well but for classes with generics.

The functions:
```kotlin
override fun <T : Any> asDocument(`object`: T): Document =
    nitriteDocumentSerializer.encodeToDocument(
        serializer = nitriteDocumentSerializer.serializersModule.serializer(`object`.javaClass),
        element = `object`
    )

@Suppress("UNCHECKED_CAST")
override fun <T> asObject(document: Document, type: Class<T>): T =
    nitriteDocumentSerializer.decodeFromDocument(
        serializer = nitriteDocumentSerializer.serializersModule.serializer(type),
        document = document
    ) as T
```
are missing information about generic types, making very hard or impossible to lookup generated serializers. In the case of `asDocument` you can use reflections to peek inside and check if there is any field that uses generics and peek inside the type of such field. Ugly and ineficcient, but doable.

In the case of  `asObject`, the field `type` of type `Class<T>` has no whatsoever information about the types. Again you could peak inside the document and figure out types, but that is very inefficient. 

The proper solution would be to pass in BOTH functions a `java.lang.reflections.Type` token, replacing `type: Class<T>` in `asObject`:

```java
interface BetterNitriteMapper {
    static Document document = new Document();
    static Object NotImplemented = new Object();

    default Document asDocument(Object object, Type type) {
        return document;
    }

    default Object asObject(Document document, Type type) {
        return document;
    }

    @Deprecated
    <T> Document asDocument(T object);

    @Deprecated
    <T> Object asObject(Document document, Class<T> type);

    boolean isValueType(Object object);
    Object asValue(Object object);
}

class Example {
    static void logic(BetterNitriteMapper mapper) {
        Document serialized = mapper.asDocument(new Object(), Object.class.getGenericSuperclass());
        if (serialized == BetterNitriteMapper.NotImplemented) {
            serialized = mapper.asDocument(new Object());
        }

        Document aDoc = new Document();
        Object deserialized = mapper.asObject(aDoc, Object.class.getGenericSuperclass());
        if (deserialized == BetterNitriteMapper.NotImplemented) {
            deserialized = mapper.asObject(aDoc, Object.class);
        }
    }
}

```

**Comment by anidotnet** [comment]
Well, now I see what you are actually looking for. You are looking for something like `TypeToken` in guava or `TypeReference` in jackson, if I am not mistaken.

The first thing is Nitrite does not support object repository of generic type, so there is no point of having a NitriteMapper which stores generic type information.

While creating object repository, you have to use raw types only. You still can store the type of the generic type parameters in a custom field inside the document and can use it later in your application.

In latest 4.2.0-SNAPSHOT, you can define your object and it's `EntityConverter` in a following way.

```java
@Data
public class GenericEntry<T> {
    private T data;
    private Long id;
    private Instant lastUpdate;

    public GenericEntry(T data, Long id, Instant lastUpdate) {
        this.data = data;
        this.id = id;
        this.lastUpdate = lastUpdate;
    }

    @SuppressWarnings("rawtypes")
    public static class GenericEntryConverter implements EntityConverter<GenericEntry> {

        @Override
        public Class<GenericEntry> getEntityType() {
            return GenericEntry.class;
        }

        @Override
        public Document toDocument(GenericEntry entity, NitriteMapper nitriteMapper) {
            return Document.createDocument("type", entity.getData().getClass().getName())
                .put("data", nitriteMapper.tryConvert(entity.data, Document.class))
                .put("id", entity.id)
                .put("lastUpdate", entity.lastUpdate);
        }

        @Override
        public GenericEntry fromDocument(Document document, NitriteMapper nitriteMapper) {
            return new GenericEntry<>(
                nitriteMapper.tryConvert(document.get("data"), Object.class),
                document.get("id", Long.class),
                document.get("lastUpdate", Instant.class));
        }
    }
}
```

**Comment by anidotnet** [comment]
Let's say the `tryConvert` method in `NitriteMapper` (in nitrite v4.2) would accept a type parameter instead of a class. I am curious to know what purpose does it serve for you in converting an object to document and vice versa? How would you want to create an object of parameterized type from a document using only Type?

Could you please show me your actual use case with some code explaining what are you trying to achieve? May be I'll be able to help you better.
