### ISSUE TITLE
IndexingException: indexing on arrays or collections for field formula are not supported

### ISSUE THREAD

**Issue by kaibioinfo** [nitrite/nitrite-java#818]
I got the following error message when indexing on a custom object:
`org.dizitart.no2.exceptions.IndexingException: NO2.5016: indexing on arrays or collections for field formula are not supported`

Indeed, the objects class implements the Iterable interface (as well as the Comparable interface). For some reason (maybe performance?) Nitrite does not want collection types or arrays as indices. However, just because a class implements Iterable does not mean its a mutable collection. Just for example: EnumSet is a wrapper around a 64bit long and would, by nitrite logic, be forbidden as index. My own custom class has an efficient Comparable implementation and is immutable, although it is more or less a collection. I don't see why it should not be allowed as index field.

**Comment by anidotnet** [comment]
Nitrite 3.x does not support index on array field. The next version 4.x has support for index on array field and much more. It is under development and will be released soon.
