### ISSUE TITLE
EntityConverter toDocument

### ISSUE THREAD

**Issue by wolfcod** [nitrite/nitrite-java#909]
I'm using Nitrite Repository to store some information inside a database, so following the documentation I wrote an EntityConverter for my object.

```java
package org.test;

import org.dizitart.no2.collection.Document;
import org.dizitart.no2.common.mapper.EntityConverter;
import org.dizitart.no2.common.mapper.NitriteMapper;
import org.dizitart.no2.repository.annotations.Id;

public class Card {

    @Id
    private String phoneNumber;
    private String firstName;
    private String lastName;

    public Card() {
        this.phoneNumber = null;
        this.firstName = null;
        this.lastName = null;
    }

    public Card(String phoneNumber, String firstName, String lastName) {
        this.phoneNumber = phoneNumber;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getFirstName() {
        return this.firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public static class Converter implements EntityConverter<Card> {

        @Override
        public Class<Card> getEntityType() {
            return Card.class;
        }

        @Override
        public Document toDocument(Card card, NitriteMapper nitriteMapper) {
            return Document.createDocument()
                    .put("phoneNumber", card.getPhoneNumber())
                    .put("firstName", card.getFirstName())
                    .put("lastName", card.getLastName());
        }

        @Override
        public Card fromDocument(Document document, NitriteMapper nitriteMapper) ....
    }
}
```

I registered the EntityConverter using  Nitrite.registerEntityConverter method, and it works fine, but, everytime I'm trying to save an object via insert into the ObjectRepository, the method toDocument is called with a unitialized object, and viceversa (an empty Document is submitted to fromDocument).

Is it the right behaviour?
Thanks

**Comment by anidotnet** [comment]
Can you please provide a reproducible code to explain the issue you are facing? I didn't understand the issue clearly. Are you saying an additional empty document getting inserted in repository every time?

**Comment by wolfcod** [comment]
No, I don't have any empty document into the repository, at least I didn't see anything into the database.
I took a look at the code, and from the stack trace and a new instance of T is created by ValidationUtils.validateRepositoryType and used with NitriteMapper.tryConvert(). In tryConvert an empty Document is submitted, and any conversion from Document to T fails because I have some primitive data type in the object.
I guess that answered to my question.

**Comment by anidotnet** [comment]
Yes you are right. The generation of empty document is part of the repository validation steps. It will not get inserted into the actual repository.

On another note, prefer non-primitive types over primitive ones for the entity, it will save you from unexpected null pointer exception during conversion.
