### ISSUE TITLE
Support JPMS

### ISSUE THREAD

**Issue by DaiYuANg** [nitrite/nitrite-java#926]

**Comment by anidotnet** [comment]
Could you please clarify what problems are you facing in non-JPMS Nitrite? And what benefits are you planning to gain by introducing JPMS?

**Comment by DaiYuANg** [comment]
> Could you please clarify what problems are you facing in non-JPMS Nitrite? And what benefits are you planning to gain by introducing JPMS?

Because I am writing a javafx desktop application, I want not import a full functional database with ORM.
So I found here, nitrite is I wanted lightly database but just not support jpms, so I can not use it in my project.

**Comment by anidotnet** [comment]
I'll support it in next minor version upgrade.

**Comment by DaiYuANg** [comment]
> I'll support it in next minor version upgrade.

Do we have daily release? I want to do some testing for nitrite integrate to my project

**Comment by anidotnet** [comment]
No we don't have daily release. There is a SNAPSHOT version that's get published nearly on weekly basis.

**Comment by anidotnet** [comment]
You can try 4.3.0-SNAPSHOT now.
