### ISSUE TITLE
Add batch replication feature

### ISSUE THREAD

**Issue by anidotnet** [nitrite/nitrite-java#95]

**Comment by TareqK** [comment]
Ello,
Can you detail a bit what you mean?

**Comment by anidotnet** [comment]
Currently during replication nitrite pushes all changes in one go to datagate server. It is not a problem if you setup replication from the beginning. But if you have large dataset already in nitrite and then you are setting replication, then it creates network bottleneck. So planning to introduce some kind of throttling and running several batches in background to upload all initial data without creating network bottleneck.

**Comment by anidotnet** [comment]
Replication has been re-written using websocket in 4.0.0
