### ISSUE TITLE
Repositories initialization logic not compatible with Kotlinx.serialization

### ISSUE THREAD

**Issue by lamba92** [nitrite/nitrite-java#966]
When creating a repository, the initialization logic goes for:
```
// stack
org.dizitart.no2.exceptions.ValidationException: Invalid repository type
    at org.dizitart.no2.common.util.ValidationUtils.validateRepositoryType(ValidationUtils.java:170)
    at org.dizitart.no2.repository.RepositoryFactory.createRepository(RepositoryFactory.java:139)
    at org.dizitart.no2.repository.RepositoryFactory.getRepository(RepositoryFactory.java:79)
    at org.dizitart.no2.NitriteDatabase.getRepository(NitriteDatabase.java:79)
```

What happens at [validateRepositoryType#L160](https://github.com/nitrite/nitrite-java/blob/7737d570860ddc5dbaacfe8bd4d486324f334346/nitrite/src/main/java/org/dizitart/no2/common/util/ValidationUtils.java#L160) is very peculiar. The function [ObjectUtils#newInstance](https://github.com/nitrite/nitrite-java/blob/7737d570860ddc5dbaacfe8bd4d486324f334346/nitrite/src/main/java/org/dizitart/no2/common/util/ObjectUtils.java#L170) is invoked in an attempt to verify if an empty document can be deserialized into an object of the type of the repository as some kind of validation step. The "magic" happens in [ObjectUtils#newInstance#L176](https://github.com/nitrite/nitrite-java/blob/7737d570860ddc5dbaacfe8bd4d486324f334346/nitrite/src/main/java/org/dizitart/no2/common/util/ObjectUtils.java#L176).

I assume that this is fine for the Java world, where when deserializing, constructor signatures are rarely respected and reflections allow you to do whatever anyway. In the Kotlin world, this is not the case and Kotlinx.serialization is meant to avoid the use of reflection or weird Java-ish checks just like the one in [ObjectUtils#newInstance#L176](https://github.com/nitrite/nitrite-java/blob/7737d570860ddc5dbaacfe8bd4d486324f334346/nitrite/src/main/java/org/dizitart/no2/common/util/ObjectUtils.java#L176). 

But why I am reporting this? The check mentioned above forced the [KotlinxSerializationMapper](https://github.com/nitrite/nitrite-java/blob/7737d570860ddc5dbaacfe8bd4d486324f334346/potassium-nitrite/src/main/kotlin/org/dizitart/kno2/serialization/KotlinXSerializationMapper.kt#L33C7-L33C33) to use the the empty document decoder [EmptyDecoder](https://github.com/nitrite/nitrite-java/blob/7737d570860ddc5dbaacfe8bd4d486324f334346/potassium-nitrite/src/main/kotlin/org/dizitart/kno2/serialization/DocumentDecoder.kt#L170) with defaults on primitives to "fake that there is something in an empty document". 

This workaround is fine most of the times, but when there are some checks on the primitives in the constructor properties of a class, things gets nasty. Look here for example:

```kotlin
@kotlinx.serialization.Serializable
data class CacheEntry(
  val sha256: String,
  val lastUpdated: kotlinx.datetime.Instant
)
```
following the workaround logic, this class will be instanciated with this code:
```kotlin
CacheEntry(
  sha256 = "",
  lastUpdated = kotlinx.datetime.Instant(java.time.Instant.parse("")) // simplified but that's the gimmick
)

db.getRepository< CacheEntry>("hashes") // KABOOOOM!
```

This will always fail because there is an attempt to create an object of type `CacheEntry` starting from an empty document [here](https://github.com/nitrite/nitrite-java/blob/7737d570860ddc5dbaacfe8bd4d486324f334346/nitrite/src/main/java/org/dizitart/no2/common/util/ObjectUtils.java#L176). 

I would recommend to remove any attempt to instanciate objects from empty documents during repository creation and just let the decoder fail at the first deserialisation of a document.

This is a blocking issue for [Package Search](https://github.com/JetBrains/package-search-intellij-plugin) to update from v3.x to v4.x.

**Comment by anidotnet** [comment]
Thanks for reporting this issue. Instead of completely removing the type validation, what if I introduce a boolean options in `NitriteConfig`. By default it will let Nitrite validate the object repository. If set, it will skip the validation. Would that work for you?

**Comment by anidotnet** [comment]
This is how, you can use it - https://github.com/nitrite/nitrite-java/blob/fbc9ecb35d239216e21e9d51971407129ec1e05e/potassium-nitrite/src/test/kotlin/org/dizitart/kno2/KotlinXSerializationMapperTest.kt#L186

**Comment by lamba92** [comment]
Perfect! I would recommend to have a `var enableRepositoryValidation = true` with default instead of a function. It would be more Kotlin concise.

**Comment by anidotnet** [comment]
Pushed the changes into the PR.

**Comment by anidotnet** [comment]
The changes are available in 4.3.0-SNAPSHOT.

**Comment by DarkAtra** [comment]
hey @anidotnet, i'm currently in the process of updating to nitrite 4.x and stumbled uppon this exact issue. Do you have any ETA on when we can expect to have this flag in a stable release?

**Comment by anidotnet** [comment]
@DarkAtra what issue exactly are you facing? Moreover, this flag is already there in latest 4.3.0-SNAPSHOT. You can try it and check if that fix your issue.

**Comment by DarkAtra** [comment]
> @DarkAtra what issue exactly are you facing? Moreover, this flag is already there in latest 4.3.0-SNAPSHOT. You can try it and check if that fix your issue.

I already validated that the snapshot indeed fixes my issue when i disable the validation. I'm just hesitant to use snapshot releases in production, that's all ^^
